% vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc', ...
% 'cudaRoot', '/usr/local/cuda-7.5/', 'enableCudnn', true, 'cudnnRoot', '/usr/local/cudnn/', ...
% 'enableImreadJpeg', true) ;

vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc', ...
'cudaRoot', '/usr/local/cuda-7.5/', 'enableCudnn', true, ...
'enableImreadJpeg', true) ;